### ISSUE TITLE
Use of react-native-vector-icons with IconWithBar ?

### ISSUE THREAD

**Issue by esutton** [alinz/react-native-tabbar#34]
Is it possible to use react-native-vector-icons with IconWithBar ?

https://github.com/oblador/react-native-vector-icons

Any suggestion are appreciated.

Thank you for a great tab bar!

**Comment by alinz** [comment]
yes, however, if you already have your font file contains all the icons, I would suggest you to use [react-native-pure-icon](https://github.com/alinz/react-native-pure-icon) instead. it's pure js and doesn't have any dependencies on native side. checkout the new version of react-native-tabbar since I have rewritten from scratch.
